// react/src/Footer.js
import React from 'react'

import ClearButton from './ClearButton'

const Footer = ({
  displayCount,
  changeFilter,
  clearAllCompleted,
  canDisplayClearButton
}) => (
  <div className="footer">
    <span className="todo-count">
      <strong>{displayCount} item left.</strong>
    </span>
    <ul className="filters">
      <li onClick={() => changeFilter('All')}>
        <a>All</a>
      </li>
      <li onClick={() => changeFilter('Active')}>
        <a>Active</a>
      </li>
      <li onClick={() => changeFilter('Completed')}>
        <a>Compeleted</a>
      </li>
    </ul>
    {canDisplayClearButton ? (
      <ClearButton clearAllCompleted={clearAllCompleted} />
    ) : null}
  </div>
)

export default Footer

// ng/src/app/footer.component.ts
import { Component, Input } from '@angular/core'

@Component({
  selector: 'app-footer',
  template: `
    <div class="footer">
      <span class="todo-count">
        <strong>{{ displayCount }} item left.</strong>
      </span>
      <ul class="filters">
        <li 
          (click)="changeFilter('All')"
        ><a>All</a></li>
        <li
          (click)="changeFilter('Active')"
        ><a>Active</a></li>
        <li
          (click)="changeFilter('Completed')"
        ><a>Completed</a></li>
      </ul>
      <button 
        class="clear-completed"
        (click)="clearAllCompleted()"
        *ngIf="canDisplayClearButton"
      >Clear completed</button>
    </div>
  `
})
export default class FooterComponent {
  @Input() displayCount: string
  @Input() changeFilter
  @Input() canDisplayClearButton
  @Input() clearAllCompleted
}
